name: Invest Burien
favicon: null
layout_spectrum: 0.2012749898713082
typography_spectrum: 0.7870358519721776
title: InvestBurien.org
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5116089996881783
  lightness: 0.6255646485369653
  saturation: 0.0841239569708705
  rhythmicContrast: 0.3303261618129909
purpose: []
